version: '3.0'

services:
  nginx:
    image: nginx:latest
    container_name: website-nginx
    restart: always
    networks:
        website-network:
    ports:
      - 80:80
    volumes:
        - website-volume:/var/lib/nginx
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
        - website-customer
        - website-admin
        - website-core

  website-database:
      image: mysql:8.0.33
      container_name: website-database
      restart: always
      networks:
        - website-network
      volumes:
        - website-volume:/var/lib/mysql
        - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      ports:
        - 3306:3306

volumes:
    website-volume:
        name: website-volume
    
networks:
    website-network:
        driver: bridge
        name: website-network